### ISSUE TITLE
ci: docker compose

### ISSUE THREAD

**Issue by shoriwe** [hawks-atlanta/metadata-scala#21]
- [x] Rename it to `docker-compose.yaml`
- [x] Force every service to just listen in `localhost`

# NOTEs

- Make sure after renaming the file it doesn't break existing pipelines

**Comment by PedroChaparro** [comment]
Hi @shoriwe, any reason for this change? We had an unique `docker-compose` file but I thought it was better to create a separated file (`docker-compose.testing.yaml`) for the `testing` and `coverage` pipelines since we don't need the `pgadmin` dashboard there .
