### ISSUE TITLE
feat: Add a way to check if a file is `ready`

### ISSUE THREAD

**Issue by Woynert** [hawks-atlanta/metadata-scala#68]
So that a client can let the user know the file is fully uploaded.

Maybe this could be added in the `GET /files/metadata/{file_uuid}` endpoint.

**Comment by PedroChaparro** [comment]
Why is this needed? Right now the `GET /files/metadata/{file_uuid}` endpoint returns a `202` status and a custom message when the file isn't ready yet. 

Maybe we can add a `GET` method to the `/ready/:fileUUID` endpoint to just return the status of a file (if needed).

**Comment by Woynert** [comment]
@PedroChaparro You are right. Thanks, I missed it.
