### ISSUE TITLE
fix: Add size field to files

### ISSUE THREAD

**Issue by andres123dbh** [hawks-atlanta/metadata-scala#85]
In the file list response, the size field would be missing since it is information that is passed to the client according to the documentation, and thus avoid having to make a call for each file to get the size. @PedroChaparro

**Comment by PedroChaparro** [comment]
I don't think the clients need it, though. Any reason to send it to the client? @andres123dbh, @Woynert.

**Comment by Woynert** [comment]
> I don't think the clients need it, though. Any reason to send it to the client? @andres123dbh, @Woynert.

According to original planning based on mimicking behavior from well know file storage services, such as Google Drive: we are storing the file size in bytes so that the client can display the file size in the listing view.

**Comment by PedroChaparro** [comment]
> According to original planning based on mimicking behavior from well know file storage services, such as Google Drive: we are storing the file size in bytes so that the client can display the file size in the listing view.

Yes, done.
