### ISSUE TITLE
fix: Nested files are not being deleted from workers

### ISSUE THREAD

**Issue by PedroChaparro** [hawks-atlanta/metadata-scala#91]
When a folder is deleted, the metadata of the nested files is deleted from the metadata database but there is no way to get the UUID of the deleted files so, **the workers cannot remove those files from the volumes**.

**Comment by PedroChaparro** [comment]
@Woynert, will we fix this? I think one possible solution could be adding a `trigger` in the `files` table so that when a record is deleted from the database, the `uuid` is saved in a new table that acts like a 'queue'. The Gateway could request these `uuids` at regular intervals and remove the corresponding files from the volumes. After removing the files, the Gateway would make another request to this service to remove the `uuids` from the 'queue'.

**Comment by shoriwe** [comment]
The only way I think this could be fixed is, after calling delete folder on the metadata endpoint return all the inside it.

BUT SINCE WE HAVE ONLY ONE WEEK LEFT TO FINISH THE PROJECT THIS FEATURE WILL BE KEEP AS **STAND BY**!

**Comment by Woynert** [comment]
As it is defined currently, there is no plan for deleting files from the workers (never delete policy), which brings certain advantages in legal terms.

However this can change if there is a team consensus. I would like to know @shoriwe's take on this.

**Comment by PedroChaparro** [comment]
> ... (never delete policy), which brings certain advantages in legal terms.
> 
Interesting :eyes:

**Comment by PedroChaparro** [comment]
> BUT SINCE WE HAVE ONLY ONE WEEK LEFT TO FINISH THE PROJECT THIS FEATURE WILL BE KEEP AS **STAND BY**!
>
OK, I'LL CLOSE THEN!
